name: pytest - PostgreSQL

on:
  push:
    branches: [ master,  github-actions-ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        db-backend: [postgres]
        python-version: [3.6, 3.7, 3.8, 3.9]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: rdmo
          POSTGRES_PASSWORD: postgres_password
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt update && sudo apt install -y pandoc texlive-xetex texlive-latex-extra texlive-fonts-recommended lmodern librsvg2-bin
        sudo apt install libpq-dev postgresql postgresql-client
        python -m pip install --upgrade pip
    - name: Install RDMO
      run: |
        pip install -e .
        pip install psycopg2-binary
        pip install coveralls
    - name: Prepare Env
      run: |
        cp testing/config/settings/${{ matrix.db-backend }}.py testing/config/settings/local.py
        cp -r testing/media testing/media_root
        mkdir testing/log
    - name: Run Tests
      run: |
        pytest --cov=rdmo
        coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
        COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls
    needs: build
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
    - name: Run Coveralls finish
      run: |
        pip install coveralls
        coveralls --service=github --finish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
